### ISSUE TITLE
Phase 2: Hello world & basic crawler app.

### ISSUE THREAD

**Issue by trungdq88** [thuhoa93/crawler#2]
Phase 2:
=================
1. [x] Create a node JS app that print “Hello world” to console.
2. [x] Use NodeJS to send a request to https://gist.github.com/trungdq88/12f20f397dd8c9af65b5a934a0e69d7e, print output to console.
3. [x] Save output to a file.
4. [x] Write instruction on how to run the program to README.

**Comment by thuhoa93** [comment]
2016/11/29: create index.js and got error when run this file 
module.js:471
    throw err;
    ^
Error: Cannot find module D:\Git\crawler\deploy\index.js

**Comment by thuhoa93** [comment]
done phase 2
